//! The authenticity-matrix config, in two layers.
//!
//! Project stance (README/ROADMAP): the authentic original behavior is
//! always the default, and every modern enhancement is an opt-in flip.
//! Until a real in-game options screen exists, the flips live in:
//!
//! - **`mgcarpet.json.defaults`** — the faithful baseline, EVERY option
//!   spelled out with its authentic value. Generated by the app when
//!   missing (delete it to refresh after an upgrade), so it doubles as
//!   the always-current option reference. Editable if you want a
//!   different baseline, but its whole point is to stay faithful.
//! - **`mgcarpet.json`** — optional, sparse: only the options you want
//!   to override, same structure as the defaults file.
//!
//! CLI flags override both for one run. Unknown fields are ignored
//! (older binaries tolerate newer configs).
//!
//! # Taxonomy
//!
//! Options are grouped first by **domain** (where they act) and, within
//! a domain, by **class** (how faithful they are). The domains:
//!
//! - **`sim`** — feeds the deterministic world model / the state-hash
//!   goldens. Any non-default here means the run is not a faithful
//!   fixture. Split into tunable `parameters` and discrete `options`.
//! - **`render`** — presentation only, never touches the sim.
//!   `enhancement` = fair visual/info opt-ins; `debug` = dev overlays
//!   that visualise the real sim (not for normal play).
//! - **`controls`** — input devices. `preferences` = neutral bindings/
//!   sensitivity; `models` = the flight-control tiers.
//! - **`audio`** — banks, voiceover, volumes. All faithful preferences.
//! - **`gameplay`** — `enhancement` = fair play opt-ins; `cheat` =
//!   otherwise-impossible power (invulnerability, all spells).
//! - **`dev`** — pure troubleshooting instruments, never gameplay.
//!
//! ```json
//! { "render": { "enhancement": { "smooth_shading": true } } }
//! ```

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

/// Default config file name, looked up in the working directory. The
/// defaults layer lives beside it as `<name>.defaults`.
pub const DEFAULT_PATH: &str = "mgcarpet.json";

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct Config {
    /// Options that feed the deterministic world model (state-hash
    /// critical — any non-default here breaks faithful fixtures).
    pub sim: SimConfig,
    /// Presentation options — never touch the sim.
    pub render: RenderConfig,
    /// Input-device options: bindings, sensitivity, flight-control tiers.
    pub controls: ControlsConfig,
    /// Audio preferences.
    pub audio: AudioConfig,
    /// Play-affecting options: fair enhancements and power cheats.
    pub gameplay: GameplayConfig,
    /// Development/troubleshooting instruments.
    pub dev: DevConfig,
    /// Where the original game installs live, for the first-run /
    /// stale-epoch auto-bake (src/bakecheck.rs). Unset = `MGC_GAMEDATA`
    /// or `gamedata/` in the working directory. A system path, outside
    /// the option taxonomy.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gamedata: Option<PathBuf>,
}

// ===========================================================================
// sim — deterministic world model (fidelity-critical)
// ===========================================================================

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct SimConfig {
    /// Tunable numeric parameters.
    pub parameters: SimParameters,
    /// Discrete sim choices (reserved: `game_speed` lands here).
    pub options: SimOptions,
}

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct SimParameters {
    /// Entity-pool capacity override (G-class — a larger pool can carry
    /// a roster the original would have dropped, so a replay taped with
    /// it enlarged is not a faithful fixture). `None` = the per-game
    /// faithful chassis default (`ChassisParams`, 1000 both games).
    /// Also settable for one run with `--pool-slots N` (2..=60000).
    pub entity_pool_size: Option<u32>,
    /// Creature wake-radius override in TILES (G-class, like the
    /// pool). `None` = the faithful 24 tiles (both retail engines,
    /// gate 0x240_0000 dist²); `Some(0)` = always awake (sleep was a
    /// period CPU optimization — asleep creatures still move but
    /// don't scan, take mail damage, or re-derive segment spacing;
    /// disabling it condenses dragons at range and applies ranged
    /// damage immediately). Also settable with `--awake-range N`
    /// (0 = off/always awake).
    pub awake_range: Option<u32>,
}

/// Discrete sim options. Empty today — reserved so `game_speed` and
/// similar tick-level choices have a faithful home when they land.
#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct SimOptions {}

// ===========================================================================
// render — presentation only
// ===========================================================================

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct RenderConfig {
    /// Neutral visual preferences (fidelity-free knobs).
    pub preference: RenderPreference,
    /// Fair visual/informational opt-ins.
    pub enhancement: RenderEnhancement,
    /// Dev overlays that visualise the real sim — not for normal play.
    pub debug: RenderDebug,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct RenderPreference {
    /// The textured parallax sky (retail's Sky option, on by
    /// default): the per-environment 256x256 cloud plane scrolled by
    /// yaw (4 wraps per revolution), slid by pitch, rolled with the
    /// bank. Off = the flat horizon-color fill (retail's sky-off
    /// keyColor). Caves never have one, exactly like retail.
    pub sky: bool,
    /// Water reflections (retail's Reflections option, on by
    /// default): sea tiles mirror the landscape about the water
    /// plane, wobbling with the wave (remc2 GRO:1104-1431 — terrain
    /// only, never sprites; our planar-mirror pass works from any
    /// altitude where retail cut off when flying high). Off = the
    /// plain animated water.
    pub reflections: bool,
    /// Dynamic light sources (retail MC2's Dynamic Lighting option,
    /// on by default): fireballs, explosions and standing fire cast
    /// a sphere of light that brightens the terrain around them —
    /// Night/Cave levels only, exactly retail's gate (remc2
    /// AddEvent2_847D0: day tables invert, added shade rows would
    /// darken). Terrain only, like retail — sprites are never lit.
    pub light_sources: bool,
    /// Fog view distance in TILES — where the distance fog fully
    /// occludes (the fade band runs 0.75·D..0.95·D, retail's hardcoded
    /// 15..19-tile ramp scaled). 20 = the retail constants (remc2
    /// GRO:668-679), which deliberately overlap the monster
    /// sight/acquisition radii (15-20 tiles) so pop-in hides in the
    /// fog; raising it reveals creatures acting before you can see
    /// them and, past ~128, the torus wrap. 0 = fog off. Max useful ≈
    /// 255 (the map is 256 tiles around — you'd see the back of your
    /// own carpet one tile short).
    pub fog_distance: u32,
}

impl Default for RenderPreference {
    fn default() -> Self {
        Self {
            sky: true,
            reflections: true,
            light_sources: true,
            fog_distance: 20,
        }
    }
}

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct RenderEnhancement {
    /// Interpolate terrain shade across tile centers instead of the
    /// original's one shade level per tile (toggle at runtime with T).
    pub smooth_shading: bool,
    /// HUD transparency (the top-strip panels + radar blend over the
    /// sky). MC1 always draws the HUD translucent; MC2 adds a toggle to
    /// make it opaque for readability (the radar especially). Multi-
    /// column matrix option: `Mc1` faithful transparent (default) |
    /// `Opaque` the MC2-style solid HUD. Player 2026-07-07: transparency
    /// "makes the radar map less useful" — opaque is the readable
    /// alternate. (Visual preference — does not affect run fidelity.)
    pub hud_transparency: HudTransparency,
    /// Highlight claimed/possessed dwellings on the overhead map in
    /// the owner's color — MC2's map behavior brought to MC1 as an
    /// opt-in (P-class; MC1 never marks houses). Player proposal
    /// 2026-07-07: "helps visibility".
    pub map_owned_buildings: bool,
    /// Tag every pickable spell jar with its granted spell's icon —
    /// on the overhead map (a small icon stamp over the jar dot) and
    /// floating over the jar in the main view. P-class level-scouting
    /// instrument (the original never labels jars; you learn by flying
    /// through). Covers MC1's class-12 jars (red AND blue) and MC2's
    /// class-15 spell tokens.
    pub expose_jar_spells: bool,
}

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct RenderDebug {
    /// Red-on-black health bars floating above monsters (toggle at
    /// runtime with H). The original never shows creature life — the
    /// combat-system debugging instrument.
    pub health_bars: bool,
    /// The autoaim crosshair (toggle at runtime with C): a
    /// white-edged black cross at the TRUE aim point (the faithful
    /// camera pitches at half the aim pitch, so aim is never screen
    /// center) plus per-hand lock markers — left `+`, right `×`,
    /// blinking red — on the target each hand's equipped spell would
    /// acquire this instant. A crude, strictly-functional
    /// projectile-behavior predictor (pure preview: no sim writes, no
    /// RNG); the original shows no aim UI at all. Acquisition ≠ hit
    /// (homing is capped 5/tick yaw).
    pub crosshair: bool,
    /// Overlay live trigger volumes / portals on the overhead map as
    /// tinted circles (toggle at runtime with V). The original never
    /// reveals trigger areas — this is a sanctioned deviation, and the
    /// event-system debugging instrument.
    pub map_trigger_areas: bool,
    /// The spawn-grace shimmer: a thin bottom-center strip draining
    /// with the respawn invulnerability window. Retail shows NOTHING
    /// for grace — the strip was a readability aid that used to draw
    /// unconditionally; it is a debug cue and defaults OFF (faithful:
    /// no grace indicator at all).
    pub grace_meter: bool,
}

// ===========================================================================
// controls — input devices
// ===========================================================================

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct ControlsConfig {
    /// Neutral input preferences (bindings, sensitivity, axis).
    pub preferences: ControlPreferences,
    /// The flight-control tiers.
    pub models: ControlModels,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct ControlPreferences {
    /// Key-binding profile. P-class, input mapping ahead of the
    /// `FlightInput` seam.
    pub bindings: Bindings,
    /// Mouse-to-stick / mouse-look sensitivity multiplier (P-class
    /// preference, 1.0 = default).
    pub mouse_sensitivity: f32,
    /// Invert the mouse Y axis (P-class binding — pure preference,
    /// changes nothing about gameplay; the originals shipped the same
    /// option). false = the authentic polarity: mouse-forward = dive,
    /// like a flight stick.
    pub invert_y: bool,
    /// The retail MC2 "Flight Assistance" option (options-menu case
    /// 5 flips `byte_0x36DEA_fly_asistant`; the idle auto-center in
    /// `sub_1A7A0` is gated on it, PI:1988): with the mouse untouched
    /// and no action for 0x30 polls the stick recenters. Applies to
    /// the faithful control model only.
    pub fly_assistant: FlyAssistant,
}

impl Default for ControlPreferences {
    fn default() -> Self {
        Self {
            bindings: Bindings::default(),
            mouse_sensitivity: 1.0,
            invert_y: false,
            fly_assistant: FlyAssistant::default(),
        }
    }
}

/// The fly-assistant idle auto-center, game-keyed like
/// [`SpellSelector`] (player ruling 2026-07-16: MC1 never had the
/// option, so its authentic default is OFF; MC2 shipped it as an
/// options toggle).
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum FlyAssistant {
    /// Each game's authentic arrangement: MC2 → on (the retail
    /// option, doing its retail job), MC1/HW → off (retail relied on
    /// the visible DOS cursor for manual centering — note we have no
    /// cursor, so a resting stick offset drifts; toggle On to trade
    /// that authenticity for stability).
    #[default]
    Auto,
    /// The assistant in every game (the MC1/HW enhancement pairing
    /// with the Backspace full stop).
    On,
    /// Never — retail-MC1 parked-deflection handling everywhere
    /// (hands-free orbiting; you trim your own drift).
    Off,
}

impl FlyAssistant {
    /// Resolve against the running game (same shape as
    /// [`SpellSelector::resolve`]).
    pub fn enabled(self, is_mc2: bool) -> bool {
        match self {
            FlyAssistant::Auto => is_mc2,
            FlyAssistant::On => true,
            FlyAssistant::Off => false,
        }
    }
}

/// The flight-control tiers (ROADMAP "Flight-control tiers"): two
/// ORTHOGONAL enums, freely combinable, authentic values as defaults.
/// Enums rather than booleans by design (authenticity-matrix rule 3 —
/// room for named alternates like `mc2` or `torso-aim` later).
#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct ControlModels {
    /// Thrust + steering model. G-CLASS (physics — a replay taped
    /// under `enhanced` is not a faithful fixture).
    pub thrust: ThrustModel,
    /// Altitude model. G-CLASS. Extended lift adds explicit float
    /// up/down keys (no original equivalent); it never bypasses wall
    /// blocking and float-up is capped at the level's highest terrain.
    pub altitude: AltitudeModel,
}

#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ThrustModel {
    /// The faithful MC1 model (remc1 sub_455D0): rate-based mouse
    /// steering (offset = turn RATE, like an airplane stick),
    /// accelerate/decelerate impulses with no stop key, thrust always
    /// in the level ground plane regardless of aim pitch.
    #[default]
    Mc1,
    /// Hold-to-fly with automatic deceleration on release (the MVP
    /// model, retuned; keeps the authentic level-plane thrust rule).
    Enhanced,
}

#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum AltitudeModel {
    /// Terrain-follow only: the carpet floats up along rising ground
    /// (hard floor ground+128) and settles by itself; no fly-up
    /// control exists (remc1 sub_455D0 vertical rules).
    #[default]
    Faithful,
    /// Faithful behavior PLUS explicit float up/down keys, with
    /// float-up capped at the level's highest terrain tile (never a
    /// god's-eye view) and wall blocking fully intact.
    ExtendedLift,
}

#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum Bindings {
    /// The original scheme: mouse aims, Up/Down arrows accelerate/
    /// decelerate, Left/Right arrows strafe.
    #[default]
    Classic,
    /// W/S thrust, A/D strafe, mouse aims (arrows keep turn/pitch in
    /// the enhanced thrust model).
    Wasd,
}

// ===========================================================================
// audio — faithful preferences
// ===========================================================================

/// Audio preferences. Volumes are plain preference, not authenticity
/// flips; the MIXER selection (faithful tile-rule vs enhanced
/// distance-weighted emitters) will join `render`/`gameplay` when the
/// enhanced mixer exists — only the faithful port is implemented.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct AudioConfig {
    /// Sample playback (F1 toggles at runtime, the original's key).
    pub sound: bool,
    /// Music playback (F2 toggles at runtime, the original's key).
    pub music: bool,
    /// Master gains, 0..=1 linear.
    pub sfx_volume: f32,
    pub music_volume: f32,
    /// Which MC1 music arrangement plays (multi-column matrix option —
    /// all three shipped on the CD as per-sound-card targets, so each
    /// column is authentic; MC2's XMI gameplay music is unaffected).
    pub arrangement: MusicArrangement,
    /// MC2 objective voiceovers (the redbook speech clips) — the
    /// original's in-game "Speech On/Off" toggle
    /// (`OptionsSettingFlag & 0x40`, remc2 PlayerInput.cpp:1221).
    pub speech: bool,
    /// Narration subtitles: the ETEXT sentence behind each objective
    /// voiceover, drawn as a top-of-screen overtitle when the cue
    /// fires. Retail MC2 shows this text INSTEAD of audio (the
    /// objective textbox is its speech-off/no-CD fallback,
    /// DrawCurrentObjectiveTextbox_30630); `auto` reproduces exactly
    /// that, `on` shows it alongside the voiceover too (the
    /// accessibility overtitle).
    pub subtitles: Subtitles,
}

impl Default for AudioConfig {
    fn default() -> Self {
        AudioConfig {
            sound: true,
            music: true,
            sfx_volume: 1.0,
            music_volume: 1.0,
            arrangement: MusicArrangement::default(),
            speech: true,
            subtitles: Subtitles::default(),
        }
    }
}

/// When narration subtitles show (see [`AudioConfig::subtitles`]).
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum Subtitles {
    /// The retail law: text exactly when the voiceover does NOT play
    /// (speech off / clips not baked) — the original's no-audio
    /// objective textbox.
    #[default]
    Auto,
    /// Always — subtitle every narration even while it plays.
    On,
    /// Never (retail with speech on shows no text either way).
    Off,
}

impl Subtitles {
    /// Should the sentence show, given whether the voiceover clip is
    /// actually about to play?
    pub fn show(self, speech_audible: bool) -> bool {
        match self {
            Subtitles::Auto => !speech_audible,
            Subtitles::On => true,
            Subtitles::Off => false,
        }
    }
}

/// MC1 shipped three interchangeable music arrangements, one per
/// sound-card family (`MUSIC<bank>-<digit>`, remc1 :54029-30): AdLib
/// FM (digit 0), Roland MT-32 (1, not baked — no MT-32 renderer), and
/// General MIDI (2). The bundle always carries the FM render; the GM
/// render (the pure-Rust oxisynth + a GM soundfont, `crate::synth`) is
/// baked when a soundfont is present — the game ships one, so GM is the
/// out-of-the-box default on every platform.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum MusicArrangement {
    /// The best-available render: General MIDI when the bundle
    /// carries it, else the FM render.
    #[default]
    Auto,
    /// Force the AdLib FM (OPL3) render — the `-0` driver's sound.
    Fm,
    /// Force the General MIDI render (falls back to FM with a console
    /// note when the bundle has no GM tracks — the shipped soundfont was
    /// missing at bake time; drop one in or set `MGC_SOUNDFONT` and
    /// rebake).
    Gm,
}

impl MusicArrangement {
    /// Resolve to the runtime preference bit ([`mgc_audio::Audio`]
    /// falls back to FM per track when GM is absent).
    pub fn prefer_gm(self) -> bool {
        !matches!(self, MusicArrangement::Fm)
    }
}

// ===========================================================================
// gameplay — play-affecting opt-ins and cheats
// ===========================================================================

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct GameplayConfig {
    /// Fair play opt-ins (still authentic-legal — no impossible power).
    pub enhancement: GameplayEnhancement,
    /// Cheats: otherwise-impossible power. Any of these on = a
    /// non-canonical run.
    pub cheat: GameplayCheat,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct GameplayEnhancement {
    /// Which spell-selection interface is live (P-class, multi-column
    /// matrix option — interface only, the spell economy underneath is
    /// untouched). MC1's faithful surface = the fullscreen-map
    /// spellbook page; MC2's = the CTRL-hold docked selector pane
    /// (with the per-spell level sub-menus). `auto` (default) = each
    /// game's own faithful surface. MC1 accepts every value —
    /// including `mc2` (the pane replaces the map book; the map's
    /// book half becomes the stretched live view, MC2-style) and
    /// `mc1+mc2` (both surfaces at once). MC2 always resolves to the
    /// pane: a 26-spell book never had an in-map grid, so `mc1`/
    /// `mc1+mc2` coerce (with a console note) rather than invent one.
    pub spell_selector: SpellSelector,
    /// Remove any spell jar whose spell the local player already owns —
    /// and therefore can never pick up. Retail (BOTH MC1 and MC2)
    /// leaves such jars in the world forever (placed jars never decay),
    /// so they become permanent, unidentifiable clutter. An INTENTIONAL
    /// deviation from retail (P-class unfaithful improvement, player-
    /// directed 2026-07-14): sweeps at level load AND the instant the
    /// player gains a spell. Single-player entity removal. The lone
    /// enhancement that defaults ON ("no one will ever complain") —
    /// disable with `--no-prune-owned-jars` for a purist run. Covers
    /// MC1's class-12 jars and MC2's class-15 spell tokens. See
    /// docs/FIDELITY.md.
    pub prune_owned_jars: bool,
}

impl Default for GameplayEnhancement {
    fn default() -> Self {
        Self {
            spell_selector: SpellSelector::default(),
            // The lone default-ON enhancement (player-directed
            // 2026-07-14): removing jars you can never pick up is
            // "one no one will ever complain about". Purists disable
            // it with `--no-prune-owned-jars`.
            prune_owned_jars: true,
        }
    }
}

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct GameplayCheat {
    /// All 24 spells granted + infinite mana (toggle at runtime with
    /// G). The spell-track playtest instrument; gameplay-affecting
    /// (G-class) — a replay taped with it on is not a faithful
    /// fixture. The original ships the equivalent debug commands
    /// ("access all spells" / "more mana", remc1's :48836 cheat menu).
    pub dev_spells: bool,
    /// Player invincibility — the pre-mortality dev behavior (damage
    /// totaled for display, never applied; no death). G-class
    /// playtest/accessibility instrument; the authentic default is
    /// MORTAL (grace window, castle respawn, castle-less death =
    /// level restart).
    pub invincible: bool,
}

#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum SpellSelector {
    /// Each game's faithful surface: MC1 → the map-screen spellbook,
    /// MC2 → the CTRL pane. The authentic default.
    #[default]
    Auto,
    /// Force the MC1 map-screen spellbook (MC1 only; MC2 coerces to
    /// the pane).
    Mc1,
    /// Force the MC2 CTRL-hold selector pane; the map screen drops
    /// its spellbook half for the stretched live view.
    Mc2,
    /// Both surfaces at once (MC1 only): the map book stays AND the
    /// CTRL pane works everywhere — the no-compromise loadout.
    #[serde(rename = "mc1+mc2")]
    Mc1Mc2,
}

/// A [`SpellSelector`] resolved against the running game: which of the
/// two selection surfaces are live this session.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SelectorSurfaces {
    /// The MC1 map-screen spellbook page (its absence also switches
    /// the map screen's book half to the stretched live view).
    pub map_book: bool,
    /// The MC2 CTRL-hold docked selector pane.
    pub ctrl_pane: bool,
}

impl SpellSelector {
    /// Resolve for the running game. MC2 has exactly one shape (the
    /// pane); anything explicitly asking for the map book there is
    /// coerced, and the caller prints the note (so the message can
    /// name the config source).
    pub fn resolve(self, is_mc2: bool) -> SelectorSurfaces {
        if is_mc2 {
            return SelectorSurfaces {
                map_book: false,
                ctrl_pane: true,
            };
        }
        match self {
            SpellSelector::Auto | SpellSelector::Mc1 => SelectorSurfaces {
                map_book: true,
                ctrl_pane: false,
            },
            SpellSelector::Mc2 => SelectorSurfaces {
                map_book: false,
                ctrl_pane: true,
            },
            SpellSelector::Mc1Mc2 => SelectorSurfaces {
                map_book: true,
                ctrl_pane: true,
            },
        }
    }
}

#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum HudTransparency {
    /// Faithful MC1: the whole HUD blends over the sky (sub_23940's
    /// blend path — transparency is always on in MC1).
    #[default]
    Mc1,
    /// Opaque HUD (MC2 offers this toggle): solid panels + radar, best
    /// readability. P-class, presentation-only.
    Opaque,
}

// ===========================================================================
// dev — troubleshooting instruments
// ===========================================================================

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct DevConfig {
    /// Seed the spellbook at level start with the spells a diligent
    /// player COULD legitimately hold entering this level — the union
    /// of every spell jar in the campaign levels before this one
    /// (MC1 only; see `campaign::plausible_spellbook`). Unlike
    /// `gameplay.cheat.dev_spells` this respects the campaign's spell
    /// economy (it never grants a spell the campaign couldn't have
    /// delivered yet), so bugs found while playtesting an individual
    /// level are real. G-class playtest instrument — NOT campaign
    /// state; a level so launched is not a faithful fixture. Grants on
    /// top of whatever the world already gave (starting spells etc.).
    pub plausible_spellbook: bool,
}

// ===========================================================================
// two-layer load
// ===========================================================================

impl Config {
    /// Load the two layers: `<path>.defaults` (generated when missing;
    /// the faithful baseline) deep-merged under `path` (optional,
    /// sparse overrides). When `explicit` is false (the default path),
    /// a missing override file simply yields the baseline; a path the
    /// user asked for must exist. Malformed JSON is always an error —
    /// better loud than silently authentic.
    pub fn load(path: &Path, explicit: bool) -> Result<Self, String> {
        let defaults_path = defaults_path(path);
        write_defaults_if_missing(&defaults_path)?;

        let mut merged = match std::fs::read_to_string(&defaults_path) {
            Ok(text) => serde_json::from_str::<serde_json::Value>(&text)
                .map_err(|e| format!("{}: {e}", defaults_path.display()))?,
            Err(_) => serde_json::Value::Object(Default::default()),
        };
        match std::fs::read_to_string(path) {
            Ok(text) => {
                let overlay = serde_json::from_str::<serde_json::Value>(&text)
                    .map_err(|e| format!("{}: {e}", path.display()))?;
                merge(&mut merged, overlay);
            }
            Err(e) if e.kind() == std::io::ErrorKind::NotFound && !explicit => {}
            Err(e) => return Err(format!("{}: {e}", path.display())),
        }
        serde_json::from_value(merged).map_err(|e| format!("{}: {e}", path.display()))
    }
}

fn defaults_path(path: &Path) -> PathBuf {
    let mut os = path.as_os_str().to_owned();
    os.push(".defaults");
    PathBuf::from(os)
}

/// Deep-merge `overlay` into `base`: objects merge key-wise, everything
/// else is replaced by the overlay value.
fn merge(base: &mut serde_json::Value, overlay: serde_json::Value) {
    match (base, overlay) {
        (serde_json::Value::Object(b), serde_json::Value::Object(o)) => {
            for (k, v) in o {
                match b.get_mut(&k) {
                    Some(slot) => merge(slot, v),
                    None => {
                        b.insert(k, v);
                    }
                }
            }
        }
        (b, o) => *b = o,
    }
}

/// Generate the faithful-baseline file so every option is spelled out
/// and discoverable. Never overwrites — delete the file to regenerate
/// after an upgrade adds options.
fn write_defaults_if_missing(path: &Path) -> Result<(), String> {
    if path.exists() {
        return Ok(());
    }
    let mut v = serde_json::to_value(Config::default()).expect("config serializes");
    if let serde_json::Value::Object(o) = &mut v {
        o.insert(
            "_readme".into(),
            serde_json::Value::String(
                "The faithful baseline — every option at its authentic value, \
                 with ONE exception: gameplay.enhancement.prune_owned_jars \
                 defaults ON (a deliberate default-on enhancement). \
                 Generated by mgcarpet (delete to regenerate after upgrades). \
                 Put your overrides in mgcarpet.json with the same structure."
                    .into(),
            ),
        );
    }
    let text = serde_json::to_string_pretty(&v).expect("config serializes");
    std::fs::write(path, text + "\n").map_err(|e| format!("{}: {e}", path.display()))?;
    println!("config: wrote faithful baseline {}", path.display());
    Ok(())
}
