//! The authenticity-matrix config, in two layers.
//!
//! Project stance (README/ROADMAP): the authentic original behavior is
//! always the default, and every modern enhancement is an opt-in flip.
//! Until a real in-game options screen exists, the flips live in:
//!
//! - **`mgcarpet.json.defaults`** — the faithful baseline, EVERY option
//!   spelled out with its authentic value. Generated by the app when
//!   missing (delete it to refresh after an upgrade), so it doubles as
//!   the always-current option reference. Editable if you want a
//!   different baseline, but its whole point is to stay faithful.
//! - **`mgcarpet.json`** — optional, sparse: only the options you want
//!   to override, same structure as the defaults file.
//!
//! CLI flags override both for one run. Unknown fields are ignored
//! (older binaries tolerate newer configs).
//!
//! ```json
//! { "enhancements": { "smooth_shading": true } }
//! ```

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

/// Default config file name, looked up in the working directory. The
/// defaults layer lives beside it as `<name>.defaults`.
pub const DEFAULT_PATH: &str = "mgcarpet.json";

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct Config {
    pub enhancements: Enhancements,
    pub audio: AudioConfig,
    pub flight: FlightConfig,
}

/// The flight-control tiers (ROADMAP "Flight-control tiers"): three
/// ORTHOGONAL enums, freely combinable, authentic values as defaults.
/// Enums rather than booleans by design (authenticity-matrix rule 3 —
/// room for named alternates like `mc2` or `torso-aim` later).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct FlightConfig {
    /// Thrust + steering model. G-CLASS (physics — a replay taped
    /// under `enhanced` is not a faithful fixture).
    pub thrust: ThrustModel,
    /// Altitude model. G-CLASS. Extended lift adds explicit float
    /// up/down keys (no original equivalent); it never bypasses wall
    /// blocking and float-up is capped at the level's highest terrain.
    pub altitude: AltitudeModel,
    /// Key-binding profile. P-class, input mapping ahead of the
    /// `FlightInput` seam.
    pub bindings: Bindings,
    /// Mouse-to-stick / mouse-look sensitivity multiplier (P-class
    /// preference, 1.0 = default).
    pub mouse_sensitivity: f32,
    /// Invert the mouse Y axis (P-class binding — pure preference,
    /// changes nothing about gameplay; the originals shipped the same
    /// option). false = the authentic polarity: mouse-forward = dive,
    /// like a flight stick.
    pub invert_y: bool,
}

#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ThrustModel {
    /// The faithful MC1 model (remc1 sub_455D0): rate-based mouse
    /// steering (offset = turn RATE, like an airplane stick),
    /// accelerate/decelerate impulses with no stop key, thrust always
    /// in the level ground plane regardless of aim pitch.
    #[default]
    Mc1,
    /// Hold-to-fly with automatic deceleration on release (the MVP
    /// model, retuned; keeps the authentic level-plane thrust rule).
    Enhanced,
}

#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum AltitudeModel {
    /// Terrain-follow only: the carpet floats up along rising ground
    /// (hard floor ground+128) and settles by itself; no fly-up
    /// control exists (remc1 sub_455D0 vertical rules).
    #[default]
    Faithful,
    /// Faithful behavior PLUS explicit float up/down keys, with
    /// float-up capped at the level's highest terrain tile (never a
    /// god's-eye view) and wall blocking fully intact.
    ExtendedLift,
}

#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum Bindings {
    /// The original scheme: mouse aims, Up/Down arrows accelerate/
    /// decelerate, Left/Right arrows strafe.
    #[default]
    Classic,
    /// W/S thrust, A/D strafe, mouse aims (arrows keep turn/pitch in
    /// the enhanced thrust model).
    Wasd,
}

impl Default for FlightConfig {
    fn default() -> Self {
        FlightConfig {
            thrust: ThrustModel::default(),
            altitude: AltitudeModel::default(),
            bindings: Bindings::default(),
            mouse_sensitivity: 1.0,
            invert_y: false,
        }
    }
}

/// Audio preferences. Volumes are plain preference, not authenticity
/// flips; the MIXER selection (faithful tile-rule vs enhanced
/// distance-weighted emitters) will join `enhancements` when the
/// enhanced mixer exists — only the faithful port is implemented.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct AudioConfig {
    /// Sample playback (F1 toggles at runtime, the original's key).
    pub sound: bool,
    /// Music playback (F2 toggles at runtime, the original's key).
    pub music: bool,
    /// Master gains, 0..=1 linear.
    pub sfx_volume: f32,
    pub music_volume: f32,
}

impl Default for AudioConfig {
    fn default() -> Self {
        AudioConfig {
            sound: true,
            music: true,
            sfx_volume: 1.0,
            music_volume: 1.0,
        }
    }
}

/// Modern-convenience switches, all defaulting to off (= authentic).
/// Grows alongside the roadmap: extended controls, savepoints, ...
#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct Enhancements {
    /// Interpolate terrain shade across tile centers instead of the
    /// original's one shade level per tile (toggle at runtime with T).
    pub smooth_shading: bool,
    /// Overlay live trigger volumes / portals on the overhead map as
    /// tinted circles (toggle at runtime with V). The original never
    /// reveals trigger areas — this is a sanctioned deviation, and the
    /// event-system debugging instrument.
    pub map_trigger_areas: bool,
    /// Red-on-black health bars floating above monsters (toggle at
    /// runtime with H). The original never shows creature life — the
    /// combat-system debugging instrument.
    pub health_bars: bool,
    /// All 24 spells granted + infinite mana (toggle at runtime with
    /// G). The spell-track playtest instrument; gameplay-affecting
    /// (G-class) — a replay taped with it on is not a faithful
    /// fixture. The original ships the equivalent debug commands
    /// ("access all spells" / "more mana", remc1's :48836 cheat menu).
    pub dev_spells: bool,
    /// Highlight claimed/possessed dwellings on the overhead map in
    /// the owner's color — MC2's map behavior brought to MC1 as an
    /// opt-in (P-class; MC1 never marks houses). Player proposal
    /// 2026-07-07: "helps visibility".
    pub map_owned_buildings: bool,
    /// Player invincibility — the pre-mortality dev behavior (damage
    /// totaled for display, never applied; no death). G-class
    /// playtest/accessibility instrument; the authentic default is
    /// MORTAL (grace window, castle respawn, castle-less death =
    /// level restart).
    pub invincible: bool,
    /// HUD transparency (the top-strip panels + radar blend over the
    /// sky). MC1 always draws the HUD translucent; MC2 adds a toggle to
    /// make it opaque for readability (the radar especially). Multi-
    /// column matrix option: `Mc1` faithful transparent (default) |
    /// `Opaque` the MC2-style solid HUD. Player 2026-07-07: transparency
    /// "makes the radar map less useful" — opaque is the readable
    /// alternate.
    pub hud_transparency: HudTransparency,
}

#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum HudTransparency {
    /// Faithful MC1: the whole HUD blends over the sky (sub_23940's
    /// blend path — transparency is always on in MC1).
    #[default]
    Mc1,
    /// Opaque HUD (MC2 offers this toggle): solid panels + radar, best
    /// readability. P-class, presentation-only.
    Opaque,
}

impl Config {
    /// Load the two layers: `<path>.defaults` (generated when missing;
    /// the faithful baseline) deep-merged under `path` (optional,
    /// sparse overrides). When `explicit` is false (the default path),
    /// a missing override file simply yields the baseline; a path the
    /// user asked for must exist. Malformed JSON is always an error —
    /// better loud than silently authentic.
    pub fn load(path: &Path, explicit: bool) -> Result<Self, String> {
        let defaults_path = defaults_path(path);
        write_defaults_if_missing(&defaults_path)?;

        let mut merged = match std::fs::read_to_string(&defaults_path) {
            Ok(text) => serde_json::from_str::<serde_json::Value>(&text)
                .map_err(|e| format!("{}: {e}", defaults_path.display()))?,
            Err(_) => serde_json::Value::Object(Default::default()),
        };
        match std::fs::read_to_string(path) {
            Ok(text) => {
                let overlay = serde_json::from_str::<serde_json::Value>(&text)
                    .map_err(|e| format!("{}: {e}", path.display()))?;
                merge(&mut merged, overlay);
            }
            Err(e) if e.kind() == std::io::ErrorKind::NotFound && !explicit => {}
            Err(e) => return Err(format!("{}: {e}", path.display())),
        }
        serde_json::from_value(merged).map_err(|e| format!("{}: {e}", path.display()))
    }
}

fn defaults_path(path: &Path) -> PathBuf {
    let mut os = path.as_os_str().to_owned();
    os.push(".defaults");
    PathBuf::from(os)
}

/// Deep-merge `overlay` into `base`: objects merge key-wise, everything
/// else is replaced by the overlay value.
fn merge(base: &mut serde_json::Value, overlay: serde_json::Value) {
    match (base, overlay) {
        (serde_json::Value::Object(b), serde_json::Value::Object(o)) => {
            for (k, v) in o {
                match b.get_mut(&k) {
                    Some(slot) => merge(slot, v),
                    None => {
                        b.insert(k, v);
                    }
                }
            }
        }
        (b, o) => *b = o,
    }
}

/// Generate the faithful-baseline file so every option is spelled out
/// and discoverable. Never overwrites — delete the file to regenerate
/// after an upgrade adds options.
fn write_defaults_if_missing(path: &Path) -> Result<(), String> {
    if path.exists() {
        return Ok(());
    }
    let mut v = serde_json::to_value(Config::default()).expect("config serializes");
    if let serde_json::Value::Object(o) = &mut v {
        o.insert(
            "_readme".into(),
            serde_json::Value::String(
                "The faithful baseline — every option at its authentic value. \
                 Generated by mgcarpet (delete to regenerate after upgrades). \
                 Put your overrides in mgcarpet.json with the same structure."
                    .into(),
            ),
        );
    }
    let text = serde_json::to_string_pretty(&v).expect("config serializes");
    std::fs::write(path, text + "\n").map_err(|e| format!("{}: {e}", path.display()))?;
    println!("config: wrote faithful baseline {}", path.display());
    Ok(())
}
