//! MC1's per-kind movement/behavior rows (`unk_98F38`, Type_156),
//! extracted verbatim from the remc1 decompilation (GPL3 assumed, as
//! vendored reference throughout this project). Generated by
//! `tools/extract-remc1-tables.py` — do not edit by hand.
//!
//! A spawn handler points the event's +156 at one row; the movement
//! core and state primitives read tuning from it. Field names keep the
//! decompile's byte-offset labels (`v_N` = offset N in the 32-byte
//! struct; the initializer's 12th value lands at offset 24 despite the
//! decompile calling it `v_22`).

/// One `unk_98F38` behavior row.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BehaviorRow {
    /// Row id (== index).
    pub v_0: i16,
    /// Max turn per tick toward the target yaw (1/2048 units).
    pub v_2: i16,
    /// Min turn per tick (the turn-rate clamp's lower bound).
    pub v_4: i16,
    pub v_6: i16,
    pub v_8: i16,
    /// Altitude band above ground (upper), engine units.
    pub v_10: i16,
    /// Altitude band above ground (lower).
    pub v_12: i16,
    /// Altitude approach step per tick (negative = drift down).
    pub v_14: i16,
    /// Slope threshold (movement block).
    pub v_16: i16,
    /// Slope threshold (secondary).
    pub v_18: i16,
    /// Terrain-capability permission mask (vs `sub_11810` type bits).
    pub v_20: u32,
    pub v_22: i16,
    /// State-tick period (aggro scan cadence).
    pub v_26: i16,
    /// Aggro radius (squared-distance scale).
    pub v_28: i16,
    /// Facing cone (1/2048 units).
    pub v_30: i16,
}

#[allow(non_snake_case, clippy::too_many_arguments)]
const fn B(
    v_0: i16, v_2: i16, v_4: i16, v_6: i16, v_8: i16, v_10: i16, v_12: i16,
    v_14: i16, v_16: i16, v_18: i16, v_20: u32, v_22: i16, v_26: i16,
    v_28: i16, v_30: i16,
) -> BehaviorRow {
    BehaviorRow {
        v_0, v_2, v_4, v_6, v_8, v_10, v_12, v_14, v_16, v_18, v_20, v_22,
        v_26, v_28, v_30,
    }
}

#[rustfmt::skip]
pub const BEHAVIOR: [BehaviorRow; 31] = [
    B(0, 56, 5, 22, 5, 1792, 0, -4, 256, 512, 0xffffffff, 3072, 50, 4096, 512),
    B(1, 22, 5, 22, 5, 1792, 0, -4, 256, 512, 0xffffffff, 2304, 40, 4096, 512),
    B(2, 113, 5, 113, 5, 1792, 0, -4, 256, 512, 0xffffffff, 2304, 40, 4096, 512),
    B(3, 17, 5, 22, 5, 1792, 0, -4, 256, 512, 0xffffffff, 2304, 40, 4096, 512),
    B(4, 11, 5, 22, 5, 1792, 0, -4, 256, 512, 0xffffffff, 2304, 40, 4096, 512),
    B(5, 5, 5, 22, 5, 1792, 0, -4, 256, 512, 0xffffffff, 2304, 40, 4096, 512),
    B(6, 0, 5, 22, 5, 1792, 0, -4, 256, 512, 0xffffffff, 2304, 40, 4096, 512),
    B(7, 256, 0, 256, 0, 1024, 128, -4, 256, 512, 0xfffffeff, 6144, 40, 8192, 512),
    B(8, 256, 5, 256, 5, 768, 128, -4, 256, 512, 0xffffffff, 6144, 40, 8192, 512),
    B(9, 56, 5, 22, 5, 1536, 512, -16, 256, 512, 0xffffffff, 3072, 50, 4096, 512),
    B(10, 22, 5, 22, 5, 256, 0, -256, 15, 512, 0xfff080fe, 2304, 40, 3072, 512),
    B(11, 22, 5, 22, 5, 1792, 512, -4, 70, 341, 0xffffffff, 3840, 40, 3840, 512),
    B(12, 34, 5, 85, 5, 0, 0, -4, 30, 341, 0xffffffff, 5120, 30, 5120, 170),
    B(13, 22, 5, 22, 5, 1280, 512, -4, 70, 512, 0xffffffff, 2304, 30, 3072, 512),
    B(14, 113, 17, 113, 17, 1792, 51, -32, 20, 512, 0xffffffff, 1536, 30, 5120, 682),
    B(15, 34, 5, 85, 5, 256, 0, -64, 20, 341, 0xfff080fe, 5120, 30, 5120, 170),
    B(16, 22, 5, 113, 0, 256, 0, -128, 20, 512, 0xfff080fe, 2560, 30, 5120, 512),
    B(17, 56, 5, 22, 5, 256, 0, -64, 20, 512, 0xfff080fe, 2304, 30, 5120, 512),
    B(18, 22, 5, 22, 5, 256, 0, -32, 20, 0, 0x1, 2304, 35, 5120, 682),
    B(19, 22, 5, 22, 5, 256, 0, -128, 20, 512, 0xfff080fe, 2304, 40, 3840, 512),
    B(20, 56, 5, 22, 5, 1280, 0, -25, 80, 512, 0xffffffff, 2304, 40, 6400, 512),
    B(21, 22, 5, 22, 5, 256, 0, -128, 20, 512, 0xfff080fe, 2304, 25, 2048, 512),
    B(22, 22, 5, 22, 5, 256, 0, -128, 20, 512, 0xfff080fe, 2304, 40, 3072, 512),
    B(23, 45, 5, 22, 5, 1792, 0, -4, 60, 512, 0xffffffff, 2304, 10, 7680, 1991),
    B(24, 22, 5, 22, 5, 256, 0, -256, 20, 512, 0x20000, 2304, 15, 3840, 512),
    B(25, 68, 5, 22, 5, 1792, 256, -8, 70, 512, 0xffffffff, 2304, 40, 4608, 512),
    B(26, 22, 5, 22, 5, 256, 0, -128, 20, 512, 0xffffffff, 2304, 40, 3072, 512),
    B(27, 22, 5, 22, 5, 256, 0, -128, 20, 512, 0xffffffff, 2304, 40, 3072, 512),
    B(28, 22, 5, 22, 5, 256, 0, -128, 20, 512, 0xffffffff, 2304, 40, 3072, 512),
    B(29, 22, 5, 22, 5, 256, 0, -128, 20, 512, 0xffffffff, 2304, 40, 3072, 512),
    B(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0, 0, 0, 0, 0),
];
