#!/usr/bin/env python3
"""Extract MC2's static engine tables from the remc2 decompilation into
crates/mgc-sim/src/mc2/ (the Phase-3 tier-2 data; ROADMAP "MULTI-GAME
ARCHITECTURE").

Tables:
  str_D7BD6[157]              (engine/Level.cpp)  behavior rows — MC1's
      Type_156 schema + a trailing flags byte (bit 1 die-on-water,
      bit 4 pack-disable, bit 8 flee/alt-chase). Layout: 0-58 = a
      typed non-row section (kept verbatim for absolute indexing),
      59-106 = the 48 model-keyed rows (base pointer = index 59),
      107/156 = zero rows, 108-155 = an unexplained duplicate copy.
      Ctors assign rows by ABSOLUTE index (Goat 98, Archers 75,
      Villager 100) — never compute 59+model.
  particlesParameters_D951C[347] (engine/Type_WORD_D951C.cpp)
      sprite/billboard parameters: word_0 = TMAPS sprite base,
      byte_12 = draw type. World extents come from each ctor's
      SetEntityShiftRot args, NOT this table (unlike MC1).
  Maths::sin_DB750[2560]        (utilities/Maths.cpp)
      the engine's signed 16.16 sine table, index i =
      sin(i * 360/2048 deg) * 0x10000; [0x200 + phase] = cos(phase).
      The (10,9) dome profile and its terrain-morph siblings read it.

Verbatim engine data — extracted, not recomputed. Rerun after remc2
updates:

    python3 tools/extract-remc2-tables.py
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "reference/remc2/remc2/engine"
OUT_DIR = ROOT / "crates/mgc-sim/src/mc2"

NUM = re.compile(r"(?<![\w.])-?(?:0x[0-9a-fA-F]+|\d+)")

HEADER = """\
//! MC2 {what} (`{sym}`), extracted verbatim from the remc2
//! decompilation (vendored reference). Generated by
//! `tools/extract-remc2-tables.py` — do not edit by hand.
"""


def rows(path, name, per_row, count):
    lines = path.read_text().splitlines()
    decl = next(i for i, ln in enumerate(lines) if name in ln and "=" in ln)
    out = []
    for ln in lines[decl + 1 :]:
        code = ln.split("//")[0].strip()
        last = code.rstrip().endswith("};")
        if last:
            code = code[: code.rindex("}")]
        vals = [int(x, 0) for x in NUM.findall(code)]
        if vals:
            if len(vals) != per_row:
                raise SystemExit(f"{name}: row {len(out)} has {len(vals)} values")
            out.append(vals)
        if last:
            break
    if len(out) != count:
        raise SystemExit(f"{name}: expected {count} rows, got {len(out)}")
    return out


def flat(path, name, count):
    """Extract a flat initializer list (any number of values per line)."""
    lines = path.read_text().splitlines()
    decl = next(i for i, ln in enumerate(lines) if name in ln and "=" in ln)
    out = []
    for ln in lines[decl + 1 :]:
        code = ln.split("//")[0].strip()
        last = code.rstrip().endswith("};")
        if last:
            code = code[: code.rindex("}")]
        out.extend(int(x, 0) for x in NUM.findall(code))
        if last:
            break
    if len(out) != count:
        raise SystemExit(f"{name}: expected {count} values, got {len(out)}")
    return out


def i16(v):
    return v - (1 << 16) if v > 0x7FFF else v


def i32(v):
    return v - (1 << 32) if v > 0x7FFFFFFF else v


def emit_behavior(rws):
    # Row: v_0, v_2, v_4..v_18 (8), v_20 (u32 mask), stuba lo, stuba hi,
    # v_26, v_28, v_30, flags, stubb-pad.
    body = []
    for r in rws:
        (
            v0,
            v2,
            v4,
            v6,
            v8,
            v10,
            v12,
            v14,
            v16,
            v18,
            v20,
            plo,
            phi,
            v26,
            v28,
            v30,
            flags,
            _pad,
        ) = r
        v22 = plo | (phi << 8)  # MC1's 12th word, split into pad bytes here
        vals = [i16(v0), i16(v2), i16(v4), i16(v6), i16(v8), i16(v10), i16(v12)]
        vals += [i16(v14), i16(v16), i16(v18)]
        s = ", ".join(str(v) for v in vals)
        body.append(
            f"    B({s}, {hex(v20)}, {i16(v22)}, {i16(v26)}, {i16(v28)}, "
            f"{i16(v30)}, {hex(flags)}),"
        )
    return "\n".join(body)


def emit_sprites(rws):
    body = []
    for r in rws:
        w0, w2, w4, sp, rot, b10, b11, b12, b13 = r
        body.append(
            f"    S({hex(w0)}, {hex(w2)}, {hex(w4)}, {sp}, {rot}, "
            f"{b10}, {b11}, {b12}, {b13}),"
        )
    return "\n".join(body)


def main():
    beh = rows(SRC / "Level.cpp", "type_str_160 str_D7BD6[157]", 18, 157)
    spr = rows(
        SRC / "Type_WORD_D951C.cpp",
        "type_WORD_D951C particlesParameters_D951C[347]",
        9,
        347,
    )
    OUT_DIR.mkdir(exist_ok=True)

    (OUT_DIR / "behavior.rs").write_text(
        HEADER.format(what="behavior rows", sym="str_D7BD6[157]")
        + """\
//!
//! MC1's `Type_156` schema plus a trailing FLAGS byte (bit 1 =
//! die-on-water :8855, bit 4 = pack-scan disable :9022, bit 8 =
//! flee/alt-chase state base+6 :9003; citations = remc2
//! EventsFunctions.cpp). Indices 0..=58 are a typed non-row section
//! and 108..=155 an in-source duplicate — kept verbatim so ABSOLUTE
//! indices match the decompile (the base pointer is index 59; ctors
//! hand-pick rows: Goat 98, Archers 75, Villager 100).

/// One `str_D7BD6` row: MC1's field labels (`v_N` = byte offset in
/// the 32-byte MC1 struct; MC2 stores v_22 in its pad bytes) plus
/// the MC2-only `flags` byte.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Mc2BehaviorRow {
    pub v_0: i16,
    pub v_2: i16,
    pub v_4: i16,
    pub v_6: i16,
    pub v_8: i16,
    pub v_10: i16,
    pub v_12: i16,
    pub v_14: i16,
    pub v_16: i16,
    pub v_18: i16,
    pub v_20: u32,
    pub v_22: i16,
    pub v_26: i16,
    pub v_28: i16,
    pub v_30: i16,
    pub flags: u8,
}

impl Mc2BehaviorRow {
    pub const DIE_ON_WATER: u8 = 1;
    pub const PACK_DISABLE: u8 = 4;
    pub const FLEE: u8 = 8;
}

#[allow(non_snake_case, clippy::too_many_arguments)]
const fn B(
    v_0: i16,
    v_2: i16,
    v_4: i16,
    v_6: i16,
    v_8: i16,
    v_10: i16,
    v_12: i16,
    v_14: i16,
    v_16: i16,
    v_18: i16,
    v_20: u32,
    v_22: i16,
    v_26: i16,
    v_28: i16,
    v_30: i16,
    flags: u8,
) -> Mc2BehaviorRow {
    Mc2BehaviorRow {
        v_0,
        v_2,
        v_4,
        v_6,
        v_8,
        v_10,
        v_12,
        v_14,
        v_16,
        v_18,
        v_20,
        v_22,
        v_26,
        v_28,
        v_30,
        flags,
    }
}

/// The model-keyed rows start here (`&str_D7BD6[59]` is the engine's
/// base pointer; remc2 Events.cpp:573/599).
pub const ROW_BASE: usize = 59;

pub const BEHAVIOR: [Mc2BehaviorRow; 157] = [
"""
        + emit_behavior(beh)
        + "\n];\n"
    )

    (OUT_DIR / "sprite_params.rs").write_text(
        HEADER.format(
            what="sprite/billboard parameters", sym="particlesParameters_D951C[347]"
        )
        + """\
//!
//! The ctor passes a row index to `SetEntityIndexAndRot_49CD0`
//! (stored in the entity's +90); `word_0` is the TMAPS sprite base
//! and `byte_12` the draw type. World extents do NOT live here —
//! each ctor sets them via its `SetEntityShiftRot_49EA0` args
//! (unlike MC1's sprite_stats).

/// One `particlesParameters_D951C` row (14 packed bytes).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Mc2SpriteParam {
    /// TMAPS sprite base index.
    pub word_0: u16,
    pub word_2: u16,
    pub word_4: u16,
    pub speed_6: u16,
    pub rot_speed_8: u16,
    pub byte_10: u8,
    pub byte_11: u8,
    /// Draw type / view selector.
    pub byte_12: u8,
    pub byte_13: u8,
}

#[allow(non_snake_case, clippy::too_many_arguments)]
const fn S(
    word_0: u16,
    word_2: u16,
    word_4: u16,
    speed_6: u16,
    rot_speed_8: u16,
    byte_10: u8,
    byte_11: u8,
    byte_12: u8,
    byte_13: u8,
) -> Mc2SpriteParam {
    Mc2SpriteParam {
        word_0,
        word_2,
        word_4,
        speed_6,
        rot_speed_8,
        byte_10,
        byte_11,
        byte_12,
        byte_13,
    }
}

pub const SPRITE_PARAMS: [Mc2SpriteParam; 347] = [
"""
        + emit_sprites(spr)
        + "\n];\n"
    )
    sin = flat(
        ROOT / "reference/remc2/remc2/utilities/Maths.cpp",
        "int32_t Maths::sin_DB750[2560]",
        2560,
    )
    body = "\n".join(
        "    " + " ".join(f"{i32(v)}," for v in sin[k : k + 8])
        for k in range(0, 2560, 8)
    )
    (OUT_DIR / "sin_lut.rs").write_text(
        HEADER.format(what="sine table", sym="Maths::sin_DB750[2560]")
        + """\
//!
//! Signed 16.16 fixed point, index i = `sin(i * 360/2048 deg) *
//! 0x10000`; `[0x200 + phase]` = cos(phase) (Maths.cpp:132/145).
//! The class-10 terrain morphs ((10,9) dome profile) read it.

pub const SIN_DB750: [i32; 2560] = [
"""
        + body
        + "\n];\n"
    )
    print(f"wrote {OUT_DIR}/behavior.rs ({len(beh)} rows)")
    print(f"wrote {OUT_DIR}/sprite_params.rs ({len(spr)} rows)")
    print(f"wrote {OUT_DIR}/sin_lut.rs ({len(sin)} values)")


if __name__ == "__main__":
    sys.exit(main())
