#!/usr/bin/env python3
"""Extract the static engine LUTs the terrain-feature pass needs from the
remc1 decompilation source into crates/mgc-sim/src/tables.rs.

Tables (remc1 sub_main.cpp):
  sin_90B4C[2048]   i32  16.16 sine, full circle = 2048 steps (line ~2742)
  cos_9134C[2048]   i32  16.16 cosine (line ~3257)
  word_9374C[258]   i16  atan LUT: ~ atan2(i,256) in 1/2048 turns (line ~3906)
  bitSqrt_41104[]   u32  Newton-sqrt seeds by highest set bit (line ~1753)
  unk_909ACx/909BCx/909ECx/909FCx  u8 [.][8][2]  building paint pairs
                          {terrain type, angle-hi-bits} (lines ~2687-2712)

These are verbatim engine data (rounding does not match a simple
round(sin*65536) reconstruction), so they are extracted rather than
recomputed. Rerun after remc1 updates:

    python3 tools/extract-remc1-tables.py   # or pass an explicit sub_main.cpp path
"""

import re
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "crates/mgc-sim/src/tables.rs"
OUT_SPRITES = (
    Path(__file__).resolve().parent.parent / "crates/mgc-sim/src/mc1_sprite_stats.rs"
)

NUM = re.compile(r"(?<![\w.])-?(?:0x[0-9a-fA-F]+|\d+)")


def extract(src_lines, name, expect):
    """Collect the integer initializer of array `name`, verbatim order."""
    decl = next(i for i, ln in enumerate(src_lines) if name in ln and "=" in ln)
    vals, started = [], False
    for ln in src_lines[decl:]:
        code = ln.split("//")[0]
        if not started:
            if "{" not in code:
                continue
            code = code.split("{", 1)[1]
            started = True
        vals += [int(x, 0) for x in NUM.findall(code)]
        if "};" in ln:
            break
    if len(vals) != expect:
        raise SystemExit(f"{name}: expected {expect} values, got {len(vals)}")
    return vals


def wrap32(v):
    """The source writes negative i32 values as u32 decimals."""
    return v - (1 << 32) if v > 0x7FFFFFFF else v


def wrap16(v):
    return v - (1 << 16) if v > 0x7FFF else v


def fmt(vals, per_line=12, wrap=wrap32):
    vals = [wrap(v) for v in vals]
    lines = []
    for i in range(0, len(vals), per_line):
        lines.append("    " + ", ".join(str(v) for v in vals[i : i + per_line]) + ",")
    return "\n".join(lines)


def fmt_pairs(vals, rows):
    # vals are flat [type, angle, type, angle, ...] over rows*8 pairs.
    out = []
    for r in range(rows):
        pairs = []
        for c in range(8):
            t, a = vals[(r * 8 + c) * 2], vals[(r * 8 + c) * 2 + 1]
            pairs.append(f"[{t:#04x}, {a:#04x}]")
        out.append("    [" + ", ".join(pairs) + "],")
    return "\n".join(out)


def main():
    src = Path(sys.argv[1] if len(sys.argv) > 1 else
               Path(__file__).resolve().parent.parent / "reference/remc1/sub_main.cpp")
    lines = src.read_text(errors="replace").splitlines()

    sin = extract(lines, "int32 sin_90B4C", 2048)
    cos = extract(lines, "int32 cos_9134C", 2048)
    atan = extract(lines, "__int16 word_9374C", 258)
    # bitSqrt_41104: declared with 64 entries; only entries for bit
    # indices 0..31 are reachable from 32-bit squares.
    decl = next(i for i, ln in enumerate(lines) if "bitSqrt_41104" in ln and "=" in ln)
    vals, started = [], False
    for ln in lines[decl:]:
        code = ln.split("//")[0]
        if not started:
            if "{" not in code:
                continue
            code = code.split("{", 1)[1]
            started = True
        vals += [int(x, 0) for x in NUM.findall(code)]
        if "};" in ln:
            break
    bitsqrt = vals[:32]

    p_ac = extract(lines, "uint8 unk_909ACx", 1 * 8 * 2)
    p_bc = extract(lines, "uint8 unk_909BCx", 3 * 8 * 2)
    p_ec = extract(lines, "uint8 unk_909ECx", 1 * 8 * 2)
    p_fc = extract(lines, "uint8 unk_909FCx", 13 * 8 * 2)

    OUT.write_text(f"""\
//! Static engine LUTs for the MC1 terrain-feature pass, extracted
//! verbatim from the remc1 decompilation (GPL3 assumed, as vendored
//! reference throughout this project). Generated by
//! `tools/extract-remc1-tables.py` — do not edit by hand.

/// 16.16 sine, full circle = 2048 steps (`sin_90B4C`).
#[rustfmt::skip]
pub const SIN: [i32; 2048] = [
{fmt(sin)}
];

/// 16.16 cosine (`cos_9134C`).
#[rustfmt::skip]
pub const COS: [i32; 2048] = [
{fmt(cos)}
];

/// Arctangent LUT (`word_9374C`): entry i ~ atan2(i, 256) in
/// 1/2048-turn units; index 256 = 256 (45 degrees).
#[rustfmt::skip]
pub const ATAN: [i16; 258] = [
{fmt(atan, wrap=wrap16)}
];

/// Newton integer-sqrt seeds by highest set bit (`bitSqrt_41104`).
#[rustfmt::skip]
pub const BIT_SQRT: [u32; 32] = [
{fmt(bitsqrt, 8)}
];

/// Building paint pairs {{terrain type, angle high bits}} by corner
/// orientation 0..7 (`unk_909ACx` / `unk_909BCx` / `unk_909ECx` /
/// `unk_909FCx`).
#[rustfmt::skip]
pub const PAINT_AC: [[[u8; 2]; 8]; 1] = [
{fmt_pairs(p_ac, 1)}
];
#[rustfmt::skip]
pub const PAINT_BC: [[[u8; 2]; 8]; 3] = [
{fmt_pairs(p_bc, 3)}
];
#[rustfmt::skip]
pub const PAINT_EC: [[[u8; 2]; 8]; 1] = [
{fmt_pairs(p_ec, 1)}
];
#[rustfmt::skip]
pub const PAINT_FC: [[[u8; 2]; 8]; 13] = [
{fmt_pairs(p_fc, 13)}
];
""")
    print(f"wrote {OUT}")
    print(f"  sin[1]={sin[1]} sin[512]={sin[512]} atan[4]={atan[4]} bitsqrt[31]={bitsqrt[31]:#x}")

    write_sprite_stats(lines)


def write_sprite_stats(lines):
    """unk_99BA0x[]: the per-entity-type sprite/render stats table
    (9 initializers per row: base, tag, 0x26, world-width, world-height,
    shade, flag, draw-type placeholder, pad), plus byte_906E8[16], the
    5-view rotation fold. Only the braced `{ ... },` rows are the table;
    the decompiler follows them with an overlapping alias array
    (word_99BA6) whose data is not part of it. The 286 rows x 14 bytes
    end exactly at the next real symbol (off_9AB44), and the largest
    sprite id (528) matches the TMAPS entry count — both confirm the
    row set."""
    decl = next(i for i, ln in enumerate(lines) if "unk_99BA0x[] =" in ln)
    rows = []
    for ln in lines[decl + 1 :]:
        code = ln.split("//")[0].strip()
        m = re.fullmatch(r"\{([^{}]*)\}[,;}]*", code)
        if not m:
            break
        vals = [int(x, 0) for x in NUM.findall(m.group(1))]
        if len(vals) != 9:
            raise SystemExit(f"unk_99BA0x row with {len(vals)} values: {ln!r}")
        rows.append(vals)
        if "};" in code:
            break

    # word_99BA6[] is the same memory at +6 bytes, and it is where the
    # decompiler kept the true var_6/var_8/var_10..13 values (the braced
    # rows zero them). Per 7-word line for row r: [var_6, var_8,
    # var_10|var_11<<8, var_12|var_13<<8, var_0, var_2, var_4 of row
    # r+1]. Merge it in, cross-checking the overlapping fields.
    decl6 = next(i for i, ln in enumerate(lines) if "word_99BA6[] =" in ln)
    words = []
    for ln in lines[decl6 + 1 :]:
        code = ln.split("//")[0]
        words += [int(x, 0) for x in NUM.findall(code)]
        if "};" in code:
            break
    for r, row in enumerate(rows):
        base = 7 * r
        if base + 4 > len(words):
            break
        row[3] = words[base]  # var_6 (world width)
        v8 = words[base + 1]
        if row[4] not in (0, v8):
            raise SystemExit(f"unk_99BA0x row {r}: var_8 mismatch {row[4]:#x} vs {v8:#x}")
        row[4] = v8
        row[5] = words[base + 2] & 0xFF  # var_10 shade
        row[6] = words[base + 2] >> 8  # var_11 flag
        row[7] = words[base + 3] & 0xFF  # var_12 draw type
        if base + 5 <= len(words) and r + 1 < len(rows) and rows[r + 1][0] != words[base + 4]:
            raise SystemExit(f"unk_99BA0x row {r + 1}: var_0 continuity broke")

    fold = extract(lines, "byte_906E8", 16)

    body = "\n".join(
        f"    S({v[0]:#06x}, {v[3]:#06x}, {v[4]:#06x}, {wrap8(v[5])}, {v[7]}),"
        for v in rows
    )
    OUT_SPRITES.write_text(f"""\
//! MC1's per-entity-type sprite/render stats (`unk_99BA0x`, merged
//! with its `word_99BA6` overlay — the decompiler split one memory
//! region into both), extracted verbatim from the remc1 decompilation
//! (GPL3 assumed, as vendored reference throughout this project).
//! Generated by `tools/extract-remc1-tables.py` — do not edit by hand.
//!
//! A level entity's spawn function assigns it a row index (the "type
//! index", entity offset 86); the row then drives billboard rendering:
//! `sprite_base` is the first TMAPS sprite id of the entity's family,
//! `height`/`width` its world size (one of them may be 0 — the
//! original derives the missing one from the sprite's pixel aspect at
//! load, sub_main.cpp:66699). `draw_type` is the static copy of how
//! facing/animation select the family member; the original refreshes
//! it at sprite-load time from the sprite's own flags high byte
//! (sub_main.cpp:66708), so `flags >> 8` in the baked sprite index is
//! equivalent. Types: 0/1 = single view; 2..=16 = animation frames;
//! 17 = 8 views + mirrored back half; 18 = 16 distinct views; 19 =
//! 5 views via [`VIEW_FOLD_5`].

/// One `unk_99BA0x` row (fields the renderer consumes; the omitted
/// ones are collision/engine bookkeeping).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SpriteStats {{
    /// First TMAPS sprite id of this type's view/animation family.
    pub sprite_base: u16,
    /// World width in engine units (256 = one tile side); 0 = derive
    /// from `height` and the sprite aspect.
    pub width: u16,
    /// World height in engine units; 0 = derive from `width`.
    pub height: u16,
    /// Shade/palette-variant selector (original `var_10`).
    pub shade: i8,
    /// View/animation selection (original `var_12`; == sprite flags
    /// high byte).
    pub draw_type: u8,
}}

#[allow(non_snake_case)]
const fn S(sprite_base: u16, width: u16, height: u16, shade: i8, draw_type: u8) -> SpriteStats {{
    SpriteStats {{ sprite_base, width, height, shade, draw_type }}
}}

/// 16 view sectors folded onto 5 sprites for draw type 19
/// (`byte_906E8`).
pub const VIEW_FOLD_5: [u8; 16] = {fold!r};

#[rustfmt::skip]
pub const SPRITE_STATS: [SpriteStats; {len(rows)}] = [
{body}
];
""")
    print(f"wrote {OUT_SPRITES} ({len(rows)} rows)")


def wrap8(v):
    return v - (1 << 8) if v > 0x7F else v


if __name__ == "__main__":
    main()
