#!/usr/bin/env python3
"""Extract the static engine LUTs the terrain-feature pass needs from the
remc1 decompilation source into crates/mgc-sim/src/tables.rs.

Tables (remc1 sub_main.cpp):
  sin_90B4C[2048]   i32  16.16 sine, full circle = 2048 steps (line ~2742)
  cos_9134C[2048]   i32  16.16 cosine (line ~3257)
  word_9374C[258]   i16  atan LUT: ~ atan2(i,256) in 1/2048 turns (line ~3906)
  bitSqrt_41104[]   u32  Newton-sqrt seeds by highest set bit (line ~1753)
  unk_909ACx/909BCx/909ECx/909FCx  u8 [.][8][2]  building paint pairs
                          {terrain type, angle-hi-bits} (lines ~2687-2712)

These are verbatim engine data (rounding does not match a simple
round(sin*65536) reconstruction), so they are extracted rather than
recomputed. Rerun after remc1 updates:

    python3 tools/extract-remc1-tables.py ~/projects/remc1/sub_main.cpp
"""

import re
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "crates/mgc-sim/src/tables.rs"

NUM = re.compile(r"(?<![\w.])-?(?:0x[0-9a-fA-F]+|\d+)")


def extract(src_lines, name, expect):
    """Collect the integer initializer of array `name`, verbatim order."""
    decl = next(i for i, ln in enumerate(src_lines) if name in ln and "=" in ln)
    vals, started = [], False
    for ln in src_lines[decl:]:
        code = ln.split("//")[0]
        if not started:
            if "{" not in code:
                continue
            code = code.split("{", 1)[1]
            started = True
        vals += [int(x, 0) for x in NUM.findall(code)]
        if "};" in ln:
            break
    if len(vals) != expect:
        raise SystemExit(f"{name}: expected {expect} values, got {len(vals)}")
    return vals


def wrap32(v):
    """The source writes negative i32 values as u32 decimals."""
    return v - (1 << 32) if v > 0x7FFFFFFF else v


def wrap16(v):
    return v - (1 << 16) if v > 0x7FFF else v


def fmt(vals, per_line=12, wrap=wrap32):
    vals = [wrap(v) for v in vals]
    lines = []
    for i in range(0, len(vals), per_line):
        lines.append("    " + ", ".join(str(v) for v in vals[i : i + per_line]) + ",")
    return "\n".join(lines)


def fmt_pairs(vals, rows):
    # vals are flat [type, angle, type, angle, ...] over rows*8 pairs.
    out = []
    for r in range(rows):
        pairs = []
        for c in range(8):
            t, a = vals[(r * 8 + c) * 2], vals[(r * 8 + c) * 2 + 1]
            pairs.append(f"[{t:#04x}, {a:#04x}]")
        out.append("    [" + ", ".join(pairs) + "],")
    return "\n".join(out)


def main():
    src = Path(sys.argv[1] if len(sys.argv) > 1 else
               Path.home() / "projects/remc1/sub_main.cpp")
    lines = src.read_text(errors="replace").splitlines()

    sin = extract(lines, "int32 sin_90B4C", 2048)
    cos = extract(lines, "int32 cos_9134C", 2048)
    atan = extract(lines, "__int16 word_9374C", 258)
    # bitSqrt_41104: declared with 64 entries; only entries for bit
    # indices 0..31 are reachable from 32-bit squares.
    decl = next(i for i, ln in enumerate(lines) if "bitSqrt_41104" in ln and "=" in ln)
    vals, started = [], False
    for ln in lines[decl:]:
        code = ln.split("//")[0]
        if not started:
            if "{" not in code:
                continue
            code = code.split("{", 1)[1]
            started = True
        vals += [int(x, 0) for x in NUM.findall(code)]
        if "};" in ln:
            break
    bitsqrt = vals[:32]

    p_ac = extract(lines, "uint8 unk_909ACx", 1 * 8 * 2)
    p_bc = extract(lines, "uint8 unk_909BCx", 3 * 8 * 2)
    p_ec = extract(lines, "uint8 unk_909ECx", 1 * 8 * 2)
    p_fc = extract(lines, "uint8 unk_909FCx", 13 * 8 * 2)

    OUT.write_text(f"""\
//! Static engine LUTs for the MC1 terrain-feature pass, extracted
//! verbatim from the remc1 decompilation (GPL3 assumed, as vendored
//! reference throughout this project). Generated by
//! `tools/extract-remc1-tables.py` — do not edit by hand.

/// 16.16 sine, full circle = 2048 steps (`sin_90B4C`).
#[rustfmt::skip]
pub const SIN: [i32; 2048] = [
{fmt(sin)}
];

/// 16.16 cosine (`cos_9134C`).
#[rustfmt::skip]
pub const COS: [i32; 2048] = [
{fmt(cos)}
];

/// Arctangent LUT (`word_9374C`): entry i ~ atan2(i, 256) in
/// 1/2048-turn units; index 256 = 256 (45 degrees).
#[rustfmt::skip]
pub const ATAN: [i16; 258] = [
{fmt(atan, wrap=wrap16)}
];

/// Newton integer-sqrt seeds by highest set bit (`bitSqrt_41104`).
#[rustfmt::skip]
pub const BIT_SQRT: [u32; 32] = [
{fmt(bitsqrt, 8)}
];

/// Building paint pairs {{terrain type, angle high bits}} by corner
/// orientation 0..7 (`unk_909ACx` / `unk_909BCx` / `unk_909ECx` /
/// `unk_909FCx`).
#[rustfmt::skip]
pub const PAINT_AC: [[[u8; 2]; 8]; 1] = [
{fmt_pairs(p_ac, 1)}
];
#[rustfmt::skip]
pub const PAINT_BC: [[[u8; 2]; 8]; 3] = [
{fmt_pairs(p_bc, 3)}
];
#[rustfmt::skip]
pub const PAINT_EC: [[[u8; 2]; 8]; 1] = [
{fmt_pairs(p_ec, 1)}
];
#[rustfmt::skip]
pub const PAINT_FC: [[[u8; 2]; 8]; 13] = [
{fmt_pairs(p_fc, 13)}
];
""")
    print(f"wrote {OUT}")
    print(f"  sin[1]={sin[1]} sin[512]={sin[512]} atan[4]={atan[4]} bitsqrt[31]={bitsqrt[31]:#x}")


if __name__ == "__main__":
    main()
